### ISSUE TITLE
pre-training weights 

### ISSUE THREAD

**Issue by gvsmothish** [waterdisappear/SAR-JEPA#1]
Dear authors,

Your work is very useful contribution to the field of SAR image analysis.
Can you make the pre-training weights download link in any other platform instead of baidu. As i cant able to download through baidu cloud because of restrictions

**Comment by waterdisappear** [comment]
May be kaggle?  https://www.kaggle.com/models/liweijie19/sar-jepa

**Comment by gvsmothish** [comment]
> May be kaggle? https://www.kaggle.com/models/liweijie19/sar-jepa

Thank you !!!

**Comment by waterdisappear** [comment]
If you find our work is useful, please give us 🌟 in GitHub and cite our paper in the following BibTex format:

```
@article{li2024predicting,
  title = {Predicting gradient is better: Exploring self-supervised learning for SAR ATR with a joint-embedding predictive architecture},
  journal = {ISPRS Journal of Photogrammetry and Remote Sensing},
  volume = {218},
  pages = {326-338},
  year = {2024},
  issn = {0924-2716},
  doi = {https://doi.org/10.1016/j.isprsjprs.2024.09.013},
  url = {https://www.sciencedirect.com/science/article/pii/S0924271624003514},
  author = {Li, Weijie and Yang, Wei and Liu, Tianpeng and Hou, Yuenan and Li, Yuxuan and Liu, Zhen and Liu, Yongxiang and Liu, Li},
}
```
