### ISSUE TITLE
Unable to access Baidu

### ISSUE THREAD

**Issue by sungbinson** [waterdisappear/SAR-JEPA#3]
I am unable to access Baidu in my country, so i cannot download the datasets through Baidu.
Would it be possible for you to upload the pretraining and finetuning datasets to Google Drive?

**Comment by waterdisappear** [comment]
Here is Kaggle link https://www.kaggle.com/models/liweijie19/sar-jepa.

**Comment by sungbinson** [comment]
> Here is Kaggle link https://www.kaggle.com/models/liweijie19/sar-jepa.

Thank you for your response. 
I have one thing to confirm.
the number of pre-training datasets used in the paper is 94,776, which is the total of four datasets, but the pre-training set I received from Kaggle contains 94,726 images. 
What is the difference between them?

**Comment by waterdisappear** [comment]
![image](https://github.com/user-attachments/assets/4dfc5d40-bc53-4ac6-a697-95cbe4213678)
